language: node_js
node_js:
  - "5"
  - "5.1"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script:
  - "npm run nsp && npm run lint && npm test"

notifications:
  email: false

sudo: false

before_install:
 - "npm install -g npm@latest"


